### ISSUE TITLE
No support for cyrillic symbols

### ISSUE THREAD

**Issue by garf** [october-widgets/tagbox#2]
Hello.
No Cyrillic symbols allowed. But the can be used very often.
Thank you.

**Comment by scottbedard** [comment]
Thanks for alerting me of this, I'll look into it when I have some time.

**Comment by vojtasvoboda** [comment]
Same problem here :-(

**Comment by vojtasvoboda** [comment]
Just turn off `slugify` param:

```
tags:
    label: Tags
    type: owl-tagbox
    slugify: false
```
